import type { CommandCenterState } from "./types";

const snapshotTime = "2026-07-20T14:30:00-04:00";

export const initialCommandCenterState: CommandCenterState = {
  generatedAt: snapshotTime,
  settings: {
    background_ai_paused: "true",
    recruiter_target_minutes: "120",
    recruiter_critical_minutes: "180",
    recruiter_hard_deadline: "same-day",
    canonical_storage: "Google Drive",
    active_approval_count: "0",
    paused_automation_count: "2",
  },
  projects: [
    {
      id: "general",
      title: "General",
      parentId: null,
      status: "Active",
      summary: "Quick questions and non-project matters that do not need continuing management.",
      userPlan: "Use voice or quick capture without deciding where the item belongs.",
      codexPlan: "Answer directly or route continuing matters into the correct managed branch.",
      timelineStatus: "Ongoing",
      benchmark: "Transient matters stay lightweight",
      sortOrder: 1,
    },
    {
      id: "neuro-div",
      title: "NEURO-DIV",
      parentId: null,
      status: "Active",
      summary: "Research, nonprofit, business strategy, marketing, architecture, ACS, and production design.",
      userPlan: "Review only decisions and approvals that materially require personal judgment.",
      codexPlan: "Build the Command Center foundation and keep canonical controls synchronized.",
      timelineStatus: "Foundation in progress",
      benchmark: "First usable Command Center",
      sortOrder: 2,
    },
    {
      id: "music",
      title: "Music",
      parentId: null,
      status: "Active",
      summary: "Archive recovery, Tap Dat App, and new music content created after the archive cutoff.",
      userPlan: "Continue creative capture without interrupting the active Command Center build.",
      codexPlan: "Keep archive, product, and new-content records distinct but cross-linked.",
      timelineStatus: "Multiple active workstreams",
      benchmark: "Clear historical cutoff and linked inventories",
      sortOrder: 3,
    },
    {
      id: "personal-admin",
      title: "Personal Life & Administration",
      parentId: null,
      status: "Planned",
      summary: "Home, bills, shopping, meals, workouts, calendars, and social logistics.",
      userPlan: "Capture naturally; do not manually categorize routine logistics.",
      codexPlan: "Prefer native reminders and calendars over AI automation.",
      timelineStatus: "Taxonomy approved",
      benchmark: "Native-first reminders and calendar routing",
      sortOrder: 4,
    },
    {
      id: "jobs-work",
      title: "Jobs / Work",
      parentId: null,
      status: "Priority build",
      summary: "Accounting work and a comprehensive job-hunt, recruiter, application, and résumé system.",
      userPlan: "Approve only consequential communications and factual résumé changes.",
      codexPlan: "Prepare recruiter intake, response drafting, résumé lineage, and application controls.",
      timelineStatus: "Architecture approved",
      benchmark: "Two-hour recruiter response target",
      sortOrder: 5,
    },
    {
      id: "communications",
      title: "Communications",
      parentId: null,
      status: "Priority build",
      summary: "Shared intake and action hub for personal Gmail, job-search Gmail, and other channels.",
      userPlan: "Use one approval queue instead of visiting separate project menus.",
      codexPlan: "Implement event-driven intake, deduplication, SLA tracking, and verified follow-through.",
      timelineStatus: "Foundation in progress",
      benchmark: "One canonical communication record per conversation",
      sortOrder: 6,
    },
  ],
  workItems: [
    {
      id: "work-acs-v01",
      projectId: "neuro-div",
      title: "Build ACS Command Center v0.1",
      owner: "Codex",
      status: "In progress",
      priority: "critical",
      attentionLane: "now",
      dueAt: "2026-07-20T23:59:00-04:00",
      blocker: null,
      sourceLabel: "Current Codex task",
      sourceUrl: null,
      updatedAt: snapshotTime,
    },
    {
      id: "work-drive-structure",
      projectId: "neuro-div",
      title: "Create canonical Drive project structure and implementation brief",
      owner: "Codex",
      status: "In progress",
      priority: "high",
      attentionLane: "now",
      dueAt: "2026-07-20T23:59:00-04:00",
      blocker: null,
      sourceLabel: "Standing storage instruction",
      sourceUrl: null,
      updatedAt: snapshotTime,
    },
    {
      id: "work-recruiter-route",
      projectId: "jobs-work",
      title: "Implement event-driven recruiter intake and SLA routing",
      owner: "Codex",
      status: "Prepared",
      priority: "high",
      attentionLane: "next",
      dueAt: "2026-07-21T17:00:00-04:00",
      blocker: "Mailbox authentication and LinkedIn notification configuration must be verified.",
      sourceLabel: "Approved architecture",
      sourceUrl: null,
      updatedAt: snapshotTime,
    },
    {
      id: "work-agent-ledger",
      projectId: "neuro-div",
      title: "Connect external ACS agent status ledger",
      owner: "Codex",
      status: "Queued",
      priority: "normal",
      attentionLane: "next",
      dueAt: null,
      blocker: null,
      sourceLabel: "ACS capability matrix",
      sourceUrl: null,
      updatedAt: snapshotTime,
    },
  ],
  approvals: [],
  communications: [],
  intakeItems: [],
  usagePreflights: [
    {
      id: "usage-command-center-build",
      activity: "ACS Command Center initial implementation",
      importanceRank: 3,
      baseCostRank: 2,
      adjustedCostRank: 2,
      maximumRuns: 1,
      expiresAt: "2026-07-21T23:59:00-04:00",
      estimatedCostBand: "medium",
      eventDriven: true,
      modelClass: "interactive Codex build",
      reasoningLevel: "bounded",
      status: "approved-active",
      rationale: "User explicitly approved the bounded implementation; no recurring automation is created.",
      createdAt: snapshotTime,
    },
    {
      id: "usage-recruiter-event",
      activity: "Recruiter message classification and response drafting",
      importanceRank: 4,
      baseCostRank: 1,
      adjustedCostRank: 1,
      maximumRuns: 1,
      expiresAt: "per-message same-day deadline",
      estimatedCostBand: "low",
      eventDriven: true,
      modelClass: "cheapest adequate classifier/drafter",
      reasoningLevel: "low unless message complexity requires escalation",
      status: "design-approved-not-enabled",
      rationale: "One event-triggered run per new message; native timers handle 90- and 150-minute escalation without AI.",
      createdAt: snapshotTime,
    },
  ],
  agentStatuses: [
    {
      id: "agent-codex",
      agent: "Codex",
      platform: "Codex desktop",
      projectId: "neuro-div",
      task: "Build ACS Command Center",
      status: "Active",
      lastSeenAt: snapshotTime,
      nextAction: "Complete the first usable dashboard, persistence, MCP surface, and canonical Drive copy.",
      blockedReason: null,
      evidence: "Current active task and local workspace writes.",
    },
    {
      id: "agent-claude",
      agent: "Claude Code",
      platform: "Claude Code",
      projectId: "neuro-div",
      task: "No active assignment in this implementation",
      status: "Available, not assigned",
      lastSeenAt: "2026-07-19T12:00:00-04:00",
      nextAction: "Optional independent review after the Codex implementation is testable.",
      blockedReason: null,
      evidence: "Repository capability snapshot; no live status call was made.",
    },
    {
      id: "agent-gemini",
      agent: "Gemini / Antigravity",
      platform: "Gemini CLI and Antigravity",
      projectId: "neuro-div",
      task: "No active assignment",
      status: "Constrained",
      lastSeenAt: "2026-07-19T12:00:00-04:00",
      nextAction: "Keep as a future participant after connector limitations are resolved.",
      blockedReason: "Gemini onboarding and Antigravity MCP notification limitations remain documented.",
      evidence: "ACS repository capability snapshot.",
    },
    {
      id: "agent-copilot",
      agent: "GitHub Copilot",
      platform: "VS Code",
      projectId: "neuro-div",
      task: "No active assignment",
      status: "Available with sign-in dependency",
      lastSeenAt: "2026-07-19T12:00:00-04:00",
      nextAction: "Use only for a bounded implementation or review task when assigned.",
      blockedReason: "Copilot GitHub sign-in was previously documented as outstanding.",
      evidence: "ACS repository capability snapshot.",
    },
  ],
};
